- name: Create Alpine RootFS EXT4 Image
        run: |
          # 1. Unduh Alpine Minirootfs ARM32
          wget https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/armhf/alpine-minirootfs-3.20.0-armhf.tar.gz

          # 2. Buat file disk ext4 kosong berukuran 300MB
          dd if=/dev/zero of=alpine-rootfs.ext4 bs=1M count=300
          mkfs.ext4 alpine-rootfs.ext4

          # 3. Mount disk dan ekstrak rootfs dengan akses sudo (bebas korupsi)
          mkdir -p mnt
          sudo mount alpine-rootfs.ext4 mnt
          sudo tar -xf alpine-minirootfs-3.20.0-armhf.tar.gz -C mnt

          # 4. Suntikkan skrip /init otomatisasi jaringan + TUN/TAP
          sudo bash -c 'cat << "EOF" > mnt/init
          #!/bin/sh
          mountpoint -q /proc || mount -t proc proc /proc
          mountpoint -q /sys || mount -t sysfs sysfs /sys
          mountpoint -q /dev || mount -t devtmpfs devtmpfs /dev

          if [ ! -e /dev/net/tun ]; then
              mkdir -p /dev/net
              mknod /dev/net/tun c 10 200
              chmod 0666 /dev/net/tun
          fi

          ip link set lo up
          ip link set eth0 up 2>/dev/null
          udhcpc -i eth0 -b -s /usr/share/udhcpc/default.script >/dev/null 2>&1

          echo "=========================================="
          echo " Alpine RootFS EXT4 Ready (No CPIO) "
          echo "=========================================="

          exec setsid cttyhack /bin/sh
          EOF'

          sudo chmod +x mnt/init
          sudo umount mnt

      - name: Upload Kernel & RootFS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arm32-alpine-bundle
          path: |
            buildroot/output/images/zImage
            alpine-rootfs.ext4
